version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      # The --stack-name is REQUIRED. Let's call our stack "HelloCICDStack"
      - sam deploy --stack-name HelloCICDStack --no-confirm-changeset --no-fail-on-empty-changeset