version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      # Added --capabilities CAPABILITY_IAM to allow creation of IAM roles
      - sam deploy --stack-name HelloCICDStack --resolve-s3 --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset