version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade aws-sam-cli
  build:
    commands:
      - sam build
  post_build:
    commands:
      # Added --resolve-s3 to let SAM automatically create an S3 bucket for the code
      - sam deploy --stack-name HelloCICDStack --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset